name: ssd1306
description: Driver for SSD1306/SH1108 OLED displays
version: 1.0.0
groups:
  - misc
code_owners:
  - UncleRus
depends:
  - i2cdev
  - log
  - esp_idf_lib_helpers
thread_safe: yes
targets:
  - esp32
  - esp8266
  - esp32s2
  - esp32c3
license: BSD-3
copyrights:
  - name: urx
    year: 2016
  - name: Zaltora
    year: 2016
  - name: UncleRus
    year: 2016
