---
components:
  - name: uln2003
    description: |
      Driver for ULN2003
    group: misc
    groups: []
    code_owners:
      - name: AMoo-Miki
    depends:
      - name: driver
      - name: esp_timer
      - name: log
      - name: esp_idf_lib_helpers
    thread_safe: yes
    targets:
      - name: esp32
      - name: esp8266
      - name: esp32s2
      - name: esp32c3
    licenses:
      - name: BSD-3
    copyrights:
      - name: AMoo-Miki
        year: 2023
